### ISSUE TITLE
Fix emmc speed

### ISSUE THREAD

**Issue by TecnoAquaPlays** [Bulgaricus/android_kernel_samsung_msm8916#1]
https://github.com/Bulgaricus/android_kernel_samsung_msm8916/blob/ff224c298d055e2413590a832820b496fffdf1fc/arch/arm/boot/dts/qcom/msm8916.dtsi#L669

You can change that "177770000" to "200000000", since you probably have a fixed emmc clock like mine, 200mhz, you can try overclocking that on clock-msm8916, I did overclock it one day, but it din't perform too well.

Oh yeah, and, emmc it's the storage clock, that means higher clocks the faster apps will open, etc.

I was wrong, you don't have the needed commit: https://github.com/Bulgaricus/android_kernel_samsung_msm8916/blob/94dfd8f6b20302259b83af158077bf4708a93b97/drivers/clk/qcom/clock-gcc-8916.c#L1205

it still is 17777, take a look at my source, you can cherry pick the commit

Here, I made it easy for you, it is those 2 commits:

https://github.com/TecnoAquaPlays/android_kernel_wingtech_msm8916/commit/817dc1b750c2655cdeb148a56d071bbbe5b0dac7#diff-284179b22ca372807b61ac4ecab588c1

https://github.com/TecnoAquaPlays/android_kernel_wingtech_msm8916/commit/28cc1a63e6f396a70f192cfd1b2781e47a6b50fe#diff-284179b22ca372807b61ac4ecab588c1

**Comment by Bulgaricus** [comment]
I know man,I have already done it in past. Right now I don't have time :)
